
// ** XML TAGS ELEMENTS**

#define XMLTAGNAME_ROOT         "Algorithme"
#define XMLTAGNAME_ROOT_COSNTS  "constantes"
#define XMLTAGNAME_ROOT_TYPES   "types"
#define XMLTAGNAME_ROOT_VARS    "variables"
#define XMLTAGNAME_ROOT_FCTS    "fonctions"
#define XMLTAGNAME_ROOT_PROCS   "procedures"
#define XMLTAGNAME_ROOT_ITEMS   "Debut"
#define XMLTAGNAME_CONST        "const"
#define XMLTAGNAME_TYPE_ARRAY   "tab"
#define XMLTAGNAME_TYPE_MATRIX  "mat"
#define XMLTAGNAME_TYPE_RECORD  "enreg"
#define XMLTAGNAME_RECORD_FIELD "champ"
#define XMLTAGNAME_TYPE_FILE    "fichier"
#define XMLTAGNAME_VAR          "var"
#define XMLTAGNAME_FCT          "fct"
#define XMLTAGNAME_PROC         "proc"
#define XMLTAGNAME_ARGMENT      "arg"
#define XMLTAGNAME_ITEM         "item"

// ** XML ATTRIBUTES ELEMENTS **

#define XMLATTRIBUTE_NAME_ITEM      "name"
#define XMLATTRIBUTE_CONST_VALUE    "valeur"
#define XMLATTRIBUTE_ARY_CONTAINT   "contenu"
#define XMLATTRIBUTE_ARY_SIZE       "taille"
#define XMLATTRIBUTE_MAT_COLUMNS_C  "colonnes"
#define XMLATTRIBUTE_MAT_ROWS_C     "lignes"
#define XMLATTRIBUTE_MAT_CONTAINT   "contenu"
#define XMLATTRIBUTE_FIELD_RCD_TYPE "type"
#define XMLATTRIBUTE_FILE_CONTAINT  "contenu"
#define XMLATTRIBUTE_VAR_CONTAINT   "type"
